# ========== Azure OpenAI ==========
AZURE_OPENAI_ENDPOINT        = "https://azaiminllm.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-4o-mini"

# ======== Azure Blob Storage ========
BLOB_ACCOUNT_URL    = "https://stbkmcasemaceiodocstec.blob.core.windows.net"
BLOB_CONTAINER_NAME = "blobbkmrelatoriostecnicos"
BLOB_AUTH_METHOD    = "service_principal"

BLOB_CLIENT_ID      = "19e1fc18-09a0-44d5-aaa6-44d578c3a039"
BLOB_TENANT_ID      = "592b5396-bf52-4b35-a844-d5ab522c3666"
